[server]
headless = true

[theme]
primaryColor = "#0078d4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f2f1"
textColor = "#323130"
font = "sans serif"

[browser]
gatherUsageStats = false
